### ISSUE TITLE
IGListAdapter+AsyncDisplayKit.h not found

### ISSUE THREAD

**Issue by huangboju** [TextureGroup/Texture#254]
I installed with carthage
IGListAdapter+AsyncDisplayKit.h not found
Xcode: 8.2.1
Carthage: 0.18.1
Language：Swift
 
but version 2.2 is ok

**Comment by garrettmoon** [comment]
@huangboju can you upload a sample project and add some repro steps? Thanks!

**Comment by huangboju** [comment]
@garrettmoon this is [Demo](https://github.com/huangboju/TextureDemo)

**Comment by rainypixels** [comment]
@garrettmoon Apologies if I filed a dupe. I added a demo project as well in #265.

**Comment by garrettmoon** [comment]
Ok, so I think I understand the issue now. Essentially, when AsyncDisplayKit is built, it's built without IGListKitSupport because `__has_include(<IGListKit/IGListKit.h>)` evaluates to false. However, when you try and build the app, it evaluates to true and the import isn't there. I'm not sure Carthage supports a good way to specify build flags when compiling frameworks (my Googles lead to nothing) but it does seem that Carthage is philosophically opposed to the idea of 'subspecs': https://github.com/Carthage/Carthage/issues/588

I think this means, to support IGListKit with Carthage we'd need to build it in by default for everyone. I'm opposed to this because I don't think the audience is large enough compared to something like PINRemoteImage (which is built in by default for Carthage users).

So I think sadly this may be a limitation of Carthage :(

It *might* be possible to create separate schemes for IGListKit which would always be built but then you could just drag that in? I'd be open to a pull request that adds support for that, but it seems like a workaround to something Carthage opposes :/

**Comment by rainypixels** [comment]
@garrettmoon Thanks for looking into it. Yeah, I'm definitely seeing [philosophical opposition](https://github.com/Carthage/Carthage/issues/1692#issuecomment-298891842) to subspecs as well, so I'm not sure a workaround using schemes makes much sense here... 

Oh, well. 😢

**Comment by nguyenhuy** [comment]
I'm gonna close this issue because it seems that there is nothing else we can do here. Feel free to reopen otherwise.
