### ISSUE TITLE
Using custom UICollectionViewLayout on ASColletionNode.

### ISSUE THREAD

**Issue by rantingmong** [TextureGroup/Texture#487]
Hello!

I have a custom-implemented `UICollectionViewLayout`. It is properly implemented and supports auto-sizing through standardised iOS APIs. That custom layout is also working properly (layout is fine and it autosizes cells properly) and we are using it in our production application.

I used that same `UICollectionViewLayout` subclass inside a `ASCollectionNode` by setting the `collectionViewLayout` property. Additionally, I also created a subclass of `ASCollectionViewLayoutInspecting` to please `ASCollectionNode`. `ASCollectionNode` has laid out the cells just fine but the auto-sizing feature is not working properly. Setting breakpoints inside `layoutAttributesForElements(in:)`, `layoutAttributesForItem(at:)`, `shouldInvalidateLayout(forPreferredLayoutAttributes:withOriginalAttributes)`, and `invalidationContext(forPreferredLayoutAttributes:withOriginalAttributes)` yields only `layoutAttributesForElements(in:)` being called.

My question now is is `ASCollectionNode` intercepting UIKit calls for laying out the cells inside? Do I have to conform to additional protocols to enable `ASCellNode` auto-sizing? I'm currently stumped and considering abandoning Texture altogether because of this. (The custom layout is much-o important for our application, and using/subclassing `UICollectionViewFlowLayout` is not an option since our layout is distinctively different)

**Comment by rantingmong** [comment]
OK never mind! Just have to implement a subclass of `ASCollectionLayoutDelegate` and set it in `ASCollectionNode`'s `init` method. Sheesh please put this in the documentation! Lost a couple of hours tracing code... 😑

**Comment by nguyenhuy** [comment]
With a custom collection layout integrated by setting `collectionViewLayout` property, you also need to implement `-constrainedSizeForItemAtIndexPath:` delegate method. That is because given an arbitrary layout, the framework can't figure out the size ranges it should use to measure cell nodes, and having valid size ranges is critical to ensure cache hits later on when the backing collection view calls `-sizeForItemAtIndexPath:`.

I'm glad you found out `ASCollectionLayoutDelegate` and pursued this approach. It is a beta API (thus declared in `ASCollectionNode+Beta`). It's the new approach we're experimenting with for collection view layout handling. It gives users much more control but also requires more responsibilities. One important note is that you need to make sure your delegate implementation follows the API requirements and is thread-safe. You can find sample code in `examples/CustomCollectionView` and built-in delegates (`ASCollectionGalleryLayoutDelegate` and `ASCollectionFlowLayoutDelegate`).

Since it's a beta API, we don't have very good documentation at the moment, partly because the API might change in the future. It would be great if you can help to improve the documentation and/or provide feedbacks. Thanks for trying it out!

**Comment by rantingmong** [comment]
I also tried implementing `constrainedSizeForItem(at:)`, but it did nothing.

I think the best way forward for me is to use `ASCollectionLayoutDelegate` but I only have one gripe about it: it lays out the whole cell data source in one go. I may have to change how I load our data set to only load a few items at the time or I I'll have to parallelise my layout operation inside `calculateLayout(with)`.

Anyways this is a great library! My boss is also ecstatic about the productivity boost this library would give. Not to mention when done right, the UI flies even on an iPad 2!

**Comment by nguyenhuy** [comment]
Yes, you can always expose just enough cells initially and gradually introduce more as user scrolls. 

You can also parallelize your cell node measurement by doing it on multiple (background) threads. The only requirement is that `calculateLayout(with)` must block the calling thread.

Depends on your layout, you can actually avoid measuring all cells in one go. That can be generally achieve if your cells have one or more intrinsic sizes. `ASCollectionGalleryLayoutDelegate` can be used as an example. If you can share more details about your custom layout, either here or in our Slack channel (http://texturegroup.org/slack.html - my handle is "huy"), I'm more than happy to discuss optimization strategies for your delegate.

**Comment by rantingmong** [comment]
Hi! Would it be possible to know if a particular `ASCollectionElement` has been updated between `calculateLayout(withContext:)` calls?

**Comment by nguyenhuy** [comment]
Could you explain a bit more on your use case?

**Comment by rantingmong** [comment]
I'd want to cache the layout computations I did with `calculateLayout(withContext:)`. For now I'm calculating the positions of the cells manually (by filling up a `NSMapTable` and passing it to the initialiser for `ASCollectionLayoutState`. I tried using an `ASLayout` to layout the collection view but it has the restriction of having `ASCellNode`s as its child layout elements.

**Comment by nguyenhuy** [comment]
I would not advise caching these layout computations. `ASDisplayNode` already caches its latest layout, and so what you're trying to cache is just a bunch of positions which should be fast to compute and is usually done in background thread most of the time.

As for the restriction, it'll be lifted once [#496](https://github.com/TextureGroup/Texture/pull/496/files#diff-0a43994cfbd9bac4a1480d4fb3de0609R127) is merged, which should happen this week.

**Comment by rantingmong** [comment]
Nice!! Looking forward for it.

**Comment by nguyenhuy** [comment]
Btw, if it's blocking you, you can always apply the change [here](https://github.com/TextureGroup/Texture/pull/496/files#diff-bd701ee6570450ceb4a484134e6e9ead) to your local copy. It basically replaces a naive for-loop with a breadth-first traversal. 

Definitely let me know if you have other problems/feedbacks. As you may already know, this is a new part of the framework that we're trying to evolve quickly and any contributions/feedbacks/questions has the potentially to make a huge impact. Cheers!
