### ISSUE TITLE
-[ASDisplayNode dealloc] - off-main-thread deallocation sometimes includes UIGestureRecognizer.

### ISSUE THREAD

**Issue by appleguy** [TextureGroup/Texture#514]
I know that a system exists to avoid off-main deallocation for instance variables that are known unsafe types. However we're seeing crashes in the case below, which is an associated object.

I don't have any clear lead on what associated object is causing this, but I'm pretty sure there is nothing at the application level that sets up such an association.

The first trace below is from ASDeallocQueue (a background thread), which is the crashing thread. The second one is from the main thread, which in this condition tends to be blocked on a runtime lock in related UIGestureRecognizer code.

Background:

<img width="404" alt="screen shot 2017-08-15 at 6 55 18 pm" src="https://user-images.githubusercontent.com/565251/29344330-e05e417e-81eb-11e7-84f2-d2c855f04dcf.png">

Main:

<img width="518" alt="screen shot 2017-08-15 at 6 55 48 pm" src="https://user-images.githubusercontent.com/565251/29344334-e60e56b8-81eb-11e7-8020-0718124f59a7.png">

**Comment by Adlai-Holler** [comment]
Hmm it looks like the gesture recognizer is an associated object (`_object_remove_associations`) so we can't catch it unfortunately. Since the association keys for an object aren't publicly available, the client code will need to defer the deallocation to the main queue on its own for these. Feel free to reopen this if we can do more on the framework side for these cases man!
