### ISSUE TITLE
When I refresh the page frequently, it has a deadlock

### ISSUE THREAD

**Issue by wangyutao0424** [TextureGroup/Texture#531]
My interface is like this: ASTableNode include ASCellNode, ASCellNode include ASCollectionNode.
When I refresh the page frequently, it has a deadlock.
![image](https://user-images.githubusercontent.com/4385589/29660090-eb20704c-88f2-11e7-9089-d7490acaa854.png)

**Comment by nguyenhuy** [comment]
Please include other threads as well since it's hard to diagnose deadlock by looking at a single thread.

**Comment by wangyutao0424** [comment]
Sorry, I didn't give you more thread information.
 I find that happens sometimes when I reuse the cell like this：

- (ASCellNode *)collectionNode:(ASCollectionNode *)collectionNode nodeForItemAtIndexPath:(NSIndexPath *)indexPath { 
    GCHpAssetsCell *elementNode = [collectionNode nodeForItemAtIndexPath:indexPath];
    if (!elementNode) {
        elementNode = [[GCHpAssetsCell alloc] init];
    }
    return elementNode;
}

If I don't do this, when I reload my cell will blink.

**Comment by nguyenhuy** [comment]
Nodes are meant to have a long lifecycle and normally you should not reuse them acrosss data reloads. "reloadData", as documented, is very expensive because the collection node needs to discard all existing cell nodes and loads new ones. Instead, please use a diff-ing algorithm to figure out the exact update operations needed and apply them in batch. One popular algorithm these days is the one provided by IGListKit.

I'm gonna close this issue for now as it is not a framework issue. Feel free to join our [Slack channel](http://texturegroup.org/slack.html) for faster Q&A!
