### ISSUE TITLE
IGListKit LT support ?

### ISSUE THREAD

**Issue by plm75** [TextureGroup/Texture#665]
Is there any "official" stance on the medium/long term prospect for supporting IGListKit in Texture ? : will there be a commitment from the Texture team to support it in the long run or should it be treated as a "proof of concept" that turned out to work very well so far, but could be dropped overnight ?

Thanks

**Comment by nguyenhuy** [comment]
@Adlai-Holler would know best.

**Comment by Adlai-Holler** [comment]
@plm75 We have some high-profile clients that are using the IGListKit support in production apps, so we won't drop it overnight. But we may not add support for future versions of IGListKit, if they change their arch or add features etc. Call it "maintenance phase" – we'll keep it running.

That said, at Pinterest we used only the `IGListKit/Diffing` subspec, and it turns out to be very flexible and reliable, and not very hard to build. And it's one less dependency.

**Comment by ay8s** [comment]
@Adlai-Holler Just a heads up we've recently also gone down the route of shifting to using the Diffing subspec instead of the full implementation. This made this way easier for things like drag and drop and reordering.
