### ISSUE TITLE
[Yoga BETA] Discussion of evolving prototype Yoga support

### ISSUE THREAD

**Issue by molon** [TextureGroup/Texture#69]
Hi,
I am an early user  and a serious supporter of `ASDK` and `Yoga`.
I am particularly excited when notice that @appleguy is adding `Yoga` support for `ASDK` today.

As a users, I has some advices to expect resonance:

- `ASDK` has so many `LayoutSpecs` (`ASStackLayoutSpec`,`ASInsetLayoutSpec` and so on). The more structured, "visually" declarative style also 
is great.(https://github.com/TextureGroup/Texture/blob/5e354c82aadcf233941742260b0d33a0c9295fc1/examples/ASDKgram/Sample/PhotoCellNode.m#L185)
But since it is based on flexbox , why not just provide basic layout and clear names same with flexbox directly. 
After all, flexbox has become a standard. If this is the case, learning costs will be low and readability will be more intuitive for experienced flexbox users, and the final layout codes would like below:
![image](https://cloud.githubusercontent.com/assets/3739161/25379428/93fa4ed6-29df-11e7-94bb-fa028e890728.png)
This is my own library based on `css-layout` , so maybe the advice is just my own feeling because of my habit. Still need resonance, because I want to use `ASDK` to write all pages in my next project. 😂

- We often encounter a scene: a cell's subview need to be hided because of data, so we need to `setHidden:` for it and change it's layout's `margin` `padding` or `removeFromSuperview`. It's so troublesome. So I advise to add a property `layoutInvalid`, a simple layout switch is used temporarily.

**Comment by appleguy** [comment]
@molon thanks for the supporting comments! It's important to note, however, that Yoga is a completely unsupported feature of the framework right now. We might close this task after some discussion, or otherwise we could keep it open as the one Yoga-related task.

I am currently experimenting with Yoga support, and actually it is being actively used in my project at the moment. However, there are some serious limitations in the current integration approach and it needs to be reworked.

If you have any ideas for how this could be done, let me know. In particular I was thinking about adding an ASYogaLayoutSpec or something similar.

Regarding your question / layoutInvalid suggestion -- the better solution for this is to always use .automaticallyManagesSubnodes = YES. Then in layoutSpecThatFits, simply leave out any subnodes that shouldn't appear. This works extremely well because it avoids the significant performance costs that do occur with the common "put the views in the hierarchy anyway, but mark them as hidden" -- this is not a good technique. Additionally, you can always use transitionLayoutWithDuration: and get a beautiful animation to add and remove any subnode changes.

A reasonable approach would be including a version of the ASYogaLayoutSpec initializer with a hidden:YES / NO at the end, and in this case, it could automatically remove any provided subnodes from the layout. It would be better if it is possible to avoid adding them, but this approach could help some complex layout code look much cleaner.

**Comment by molon** [comment]
@appleguy Thanks, I agree with your answer and look forward to your `ASYogaLayoutSpec `。:)

I summed up my ideas:
- The readability for hierarchy of views.
- The readability to experienced `flexbox` users. (Using original `flexbox` property names)
- The `YES/NO` which indicates `remove/add` is useful. It just like `display:none/block` of `css`.

**Comment by appleguy** [comment]
Thanks @molon ! :) Very happy to be working with you on this.

BTW, what do you think is more readable about the hierarchy of views?

i totally understand what you mean about the flexbox readability / standardization benefit (this is a non-benefit for many iOS users, but it is a real benefit for many users coming from the web). This is a pretty unique benefit of Yoga.

I also know what you mean about the value of the YES / NO option (although this could also be added to the other layout specs, so is not necessarily unique to Yoga.

**Comment by molon** [comment]
@appleguy I'm very happy too. :)

More readable about the hierarchy of views on my thoughts. (See image in floor.1)
It's just my code style, so it's not very important. Free your style~

Our ideas are very consistent, so only left with expectancy for me on this now. :)

**Comment by nguyenhuy** [comment]
I'm down for ASYogaLayoutSpec if we can pull it off!  It seems to be a much cleaner approach to integrate Yoga.  Please let me know if there is anything I can help!

**Comment by nguyenhuy** [comment]
Yoga integration has been supported for a while and shipped in production in some large apps. I'm gonna close this issue but feel free to reopen it if either of you wants to continue the discussion.
