### ISSUE TITLE
GIF not cached

### ISSUE THREAD

**Issue by harri121** [TextureGroup/Texture#817]
I am using ASNetworkImageNode to display remote GIFs. The GIFs are not cached but downloaded everytime they are displayed. Not animated images are cached properly.
Am I missing something? Do I have to write a custom cache to cache GIFs?

**Comment by dhavalcue** [comment]
I’m seeing a similar issue. Any workarounds @harri121?

**Comment by vldalx** [comment]
I've got the same issue.

Actually, animated images are cached, but `ASNetworkImageNode` ignores them and downloads every time.

The problem is here
https://github.com/TextureGroup/Texture/blob/2e95f5503eed6ac766e2b7a293a33b0c5722bca1/Source/ASNetworkImageNode.mm#L784-L788
`ASNetworkImageNode` checks if `imageContainer` keeps an image, but doesn't checks if the one keeps an animated image.

the `if` condition should be like this
``` Objective-C
[imageContainer asdk_image] == nil && [imageContainer asdk_animatedImageData] == nil && _downloader != nil
```

**Comment by vldalx** [comment]
@texturegroup please, take a look at this issue. the one doesn't seem hard to fix

**Comment by SolorzanoJose** [comment]
@TextureGroup can you implement the fix provided above?

**Comment by harri121** [comment]
+1

**Comment by strangeliu** [comment]
+1

**Comment by lxzzzzzz** [comment]
I have the same problem. How did you solve it?

**Comment by SolorzanoJose** [comment]
@lxzzzzzz there's no way to solve it, these guys need to accept the merge for the fix...

**Comment by ay8s** [comment]
Don't see a PR for this. Feel free to submit one. 👍
