### ISSUE TITLE
[ASCollectionNode _removeFromSupernode] Crash

### ISSUE THREAD

**Issue by zhuamaodeyu** [TextureGroup/Texture#846]
I used Texture for the first time, but there was a crash that I couldn’t handle.i need you help，think you very mach.  

![snip20180322_39](https://user-images.githubusercontent.com/32094174/37757454-113feef2-2de8-11e8-8dbc-f0a40f12d034.png)

i has e ASViewController , this controller has a ASTableNode , ASCellNode  has a ASCollectionNode , but i reloadData for ASTableNode , this has a crash from `[ASCollectionNode _removeFromSupernode] `.  

####crash 
```
2018-03-22 15:34:59.530 LiveTeach-iPhone[70317:30960821] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Incorrect display node thread affinity - this method should not be called off the main thread after the ASDisplayNode's view or layer have been created'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106375f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000109186deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106375dca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x0000000107012ae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   LiveTeach-iPhone                    0x000000010557482c -[ASDisplayNode _removeFromSupernode] + 332
	5   LiveTeach-iPhone                    0x000000010556eafe -[ASDisplayNode _insertSubnode:atSubnodeIndex:sublayerIndex:andRemoveSubnode:] + 2830
	6   LiveTeach-iPhone                    0x0000000105570011 -[ASDisplayNode _addSubnode:] + 1297
	7   LiveTeach-iPhone                    0x000000010556fabc -[ASDisplayNode addSubnode:] + 60
	8   LiveTeach-iPhone                    0x000000010530833f -[LTProcessCellView initWithModel:] + 3167
	9   LiveTeach-iPhone                    0x00000001052ebb40 __64-[LTProcessViewController tableNode:nodeBlockForRowAtIndexPath:]_block_invoke + 160
	10  LiveTeach-iPhone                    0x0000000105658458 __51-[ASTableView dataController:nodeBlockAtIndexPath:]_block_invoke_2 + 104
	11  LiveTeach-iPhone                    0x00000001054c96af -[ASCollectionElement node] + 127
	12  LiveTeach-iPhone                    0x000000010551731a __58-[ASDataController _allocateNodesFromElements:completion:]_block_invoke + 154
	13  LiveTeach-iPhone                    0x00000001055292bd __ASDispatchApply_block_invoke + 93
	14  libdispatch.dylib                   0x000000010a58cef9 _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x000000010a5ad49b _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010a595c8b _dispatch_root_queue_drain + 1829
	17  libdispatch.dylib                   0x000000010a595561 _dispatch_worker_thread3 + 111
	18  libsystem_pthread.dylib             0x000000010a8d81ca _pthread_wqthread + 1387
	19  libsystem_pthread.dylib             0x000000010a8d7c4d start_wqthread + 13
)
```

**Comment by zhuamaodeyu** [comment]
I can't visit slack,sorry

**Comment by zhuamaodeyu** [comment]
![snip20180322_40](https://user-images.githubusercontent.com/32094174/37758239-72f14db0-2dea-11e8-9481-f55c0f1620d9.png)

**Comment by shevakuilin** [comment]
hi, I encountered the same problem. Is there a solution?

**Comment by shevakuilin** [comment]
![asdk_issues](https://user-images.githubusercontent.com/18067718/39511978-df8ea0a6-4e21-11e8-8aa2-dedcfc1d8b77.jpeg)

**Comment by shevakuilin** [comment]
![asdk_issues](https://user-images.githubusercontent.com/18067718/39512065-221b8b32-4e22-11e8-9bd0-65be71c2f331.jpeg)

**Comment by shevakuilin** [comment]
When I comment out the following code, this error does not reappear
`collectionNode.view.showsVerticalScrollIndicator = false`

**Comment by nguyenhuy** [comment]
It looks like you're trying to allocating an `LTProcessCellView` from a background thread which is not a good idea because of per UIKit limitations. I'd suggest to either wrap that view in a display node, or allocate it on background before using in the node block.

As for the crash, it appears that the crashing node is already loaded, i.e its view/layer was initiated which happened during the first call to the node's `view` or `layer` accessor. Once a node is loaded, it can only be safely modified on the main thread. Thus, please make sure to 1) Avoid accessing a node's view/layer in the initializer, and 2) Defer any operations on the view/layer until `didLoad`, similar to what @shevakuilin and @xiaohundan mentioned above.

For references, the same details mentioned above are stated in the documentation [here](http://texturegroup.org/docs/faq.html#accessing-the-nodes-view-before-it-is-loaded) and [here](http://texturegroup.org/docs/subclassing.html#-didload).

I'm going to close this ticket, but feel free to re-open it if you still have questions regarding this crash. Thanks!
