### ISSUE TITLE
Why Range Visualization debug feature always showed

### ISSUE THREAD

**Issue by smoothdvd** [TextureGroup/Texture#90]
I didn't add code [ASDisplayNode setShouldShowRangeDebugOverlay:YES] in AppDelegate.m, even not include AsyncDisplayKit+Debug.h

**Comment by smoothdvd** [comment]
Sorry, I insert a code: ASDisplayNode.shouldShowRangeDebugOverlay = YES;

**Comment by appleguy** [comment]
@smoothdvd could you clarify what the problem is? Maybe send a screenshot?

I have never heard a report of the range visualizer showing up unexpectedly. So make sure you search your entire project for the string "RangeDebugOverlay" (in case maybe another file is using the property syntax) and see if it is getting set anywhere.

Note it does not have to be in the AppDelegate. Anywhere in the app will cause it to show up, as long as it is set before a given range controller is created.

**Comment by appleguy** [comment]
:) Thanks for updating - I was thinking it could've been that class method / property syntax! Glad you found it, hope we can help any other issues you run into.

**Comment by smoothdvd** [comment]
@appleguy Is it a bug of Range Visualization debug feature:
Start a view controller A and a ASPagerNode in it, when I push view controller B from A and dismiss it, Range Visualization will lead exception.
If start a view controller A and move ASPageNode's pager to index 2, push view controller B from A and dismiss it, there no error.
