### ISSUE TITLE
ASNetworkImageNode ! help,help,help!

### ISSUE THREAD

**Issue by aimm** [TextureGroup/Texture#901]
The avatarNode is in a table cell Node, it can display correctly at the first time the table loaded,then the images all disappeared after I scroll the cell node out of the screen ,even the placeholderimage/placeholdercolor did disappear. Here is the code:
_avatarNode = [[ASNetworkImageNode alloc] init];
_avatarNode.defaultImage = [UIImage as_imageNamed:@"placeholder"];
_avatarNode.style.preferredSize = CGSizeMake(AdaptedDimension(54), AdaptedDimension(54));
_avatarNode.URL = [NSURL URLWithString:@"https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=4064501590,587370452&fm=27&gp=0.jpg"];
Can anybody help me ???

**Comment by aimm** [comment]
and when I changed the image url to http://img0.imgtn.bdimg.com/it/u=1626113549,1123550683&fm=200&gp=0.jpg,it works well! So that's going on?

**Comment by hashemp206** [comment]
I have the same issue, when I disable caching and  I scroll up to view downloaded images, I see they have been disappeared. it seem when cells, enter preload state, NetworkImageNode fires download image request because cache has set to nil. I'm wondering why it doesn't use user memory cache by default?

**Comment by dklinzh** [comment]
You can figure it out at #925

**Comment by Adlai-Holler** [comment]
Sorry folks for this issue. The fix is landed into master!
