### ISSUE TITLE
app screen is stuck

### ISSUE THREAD

**Issue by fuhailong** [TextureGroup/Texture#928]
I have a tableNode (section:1, line :> 150), and when I want to delete the data from the last row of cellNode, the screen is blocked. When I delete the previous cellNode, there is no blocking. I tried reloadData, deleteRows, and reloadSections to get stuck. So I think that when the data is more, the data that's behind the refresh will get stuck, and it can be copied 100% of the time. Please take a look at the aforementioned questions. It's been a long time.

**Comment by nguyenhuy** [comment]
As mentioned in the [documentation](http://texturegroup.org/appledoc/Classes/ASCollectionNode.html#//api/name/reloadData) and briefly discussed [here](https://github.com/TextureGroup/Texture/issues/531#issuecomment-324599950), reload methods are very expensive and should be avoided to prevent frame drops. The recommended way to delete some rows is to indeed use `deleteRows`.

Having said that, I'd guess that you're actually facing a deadlock. To be able to help you diagnose the root cause, I'd need more information, like stack trace of *all* the threads when the deadlock occurs, and ideally a sample project that can reliably reproduce this problem.
